services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=false"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"


  xapi:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xapi.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/data/xAPI`)"
      - "traefik.http.routers.xapi.entrypoints=websecure"
      - "traefik.http.routers.xapi.tls=true"
      - "traefik.http.routers.xapi.tls.certresolver=le"
      - "traefik.http.services.xapi.loadbalancer.server.port=${API_PORT}"


  ui:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.ui.entrypoints=websecure"
      - "traefik.http.routers.ui.tls=true"
      - "traefik.http.routers.ui.tls.certresolver=le"
      - "traefik.http.services.ui.loadbalancer.server.port=${UI_PORT}"
