services:
  traefik:
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"


  xapi:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xapi.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/data/xAPI`)"
      - "traefik.http.routers.xapi.entrypoints=web"
      - "traefik.http.services.xapi.loadbalancer.server.port=${API_PORT}"


  ui:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.ui.entrypoints=web"
      - "traefik.http.services.ui.loadbalancer.server.port=${UI_PORT}"
